name: rembirth
description: "A minimalistic app to help you remember your friends' birthdays."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  permission_handler: ^12.0.1
  collection: ^1.19.1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^4.1.1
  intl: ^0.20.2
  isar_community: 3.3.0-dev.3
  isar_community_flutter_libs: 3.3.0-dev.3
  logger: ^2.5.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  isar_community_generator: 3.3.0-dev.3
  analyzer: 8.3.0

flutter:
  generate: true
  uses-material-design: true
